---
- name: 'Copy the logrotate template to /etc/logrotate.d'
  tags: 'logrotate'
  sudo: 'yes'
  template: >
    src=logrotate_config.j2
    dest=/etc/logrotate.d/{{ logrotate_conf_name }}
    owner=root
    group=root
